# Generated by Django 5.1.3 on 2024-11-24 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_member_emergency_contact_member_join_date_and_more'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('unbooked', 'Unbooked'), ('attended', 'Attended'), ('canceled', 'Canceled')], default='unbooked', max_length=20)),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.member')),
            ],
        ),
    ]
