# Generated by Django 5.1.3 on 2024-11-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='membership/image')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validity', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('auto_renew', models.BooleanField(default=False)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
