# Generated by Django 5.1.3 on 2024-11-24 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_member_emergency_contact_member_join_date_and_more'),
        ('membership', '0002_remove_membership_auto_renew_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('auto_renew', models.BooleanField(default=False)),
                ('purchase_on', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.member')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.membership')),
            ],
        ),
    ]
